language: python
python:
  - "3.4"
cache: pip
install:
  - pip install Django==1.8 testfixtures==5.0.0 coverage==4.4.1 python-codacy-coverage 
script:
  - python -m unittest discover
after_script:
  - bash code_coverage.sh
