language: python
python:
  - "3.4"
cache: pip
install:
  - pip install pipenv
  - export VENV_HOME_DIR=$(pipenv --venv)
  - pipenv sync
script:
  - pipenv run python -m unittest discover
after_script:
  - bash code_coverage.sh
